services:
 caddy:
   build:
     context: .
     dockerfile: ./caddy_chatbot/Dockerfile
   image: caddy:latest
   container_name: caddy
   ports:
    - "8080:8080"
   volumes:
    - type: bind
      source: ./pyproject.toml
      target: /caddy_chatbot/pyproject.toml
    - type: bind
      source: ./caddy_chatbot/src
      target: /caddy_chatbot
    - ~/.aws/:/root/.aws:ro
   networks:
    - caddy
   env_file:
    - .env
   environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
   networks:
     - caddy

networks:
  caddy:
