[tool.poetry]
name = "caddy-chatbot"
version = "0.0.9"
description = "An AI powered copilot for customer service agents"
authors = ["i.AI <i-dot-ai-enquiries@cabinetoffice.gov.uk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.6.4"
uvicorn = "^0.29.0"
langchain = "^0.1.13"
anthropic = "^0.21.3"
jupyter = "^1.0.0"
boto3 = "^1.34.70"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
