# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "CaddyStack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "CaddyStack"
resolve_image_repos = true
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "StageName=\"prod\" UserTableName=\"caddyUsers\" MessageTableName=\"caddyMessages\" ResponsesTableName=\"caddyResponses\" IdempotencyTableName=\"caddyIdempotency\" OfficesTableName=\"caddyOffices\" EvaluationTableName=\"caddyEvaluation\" CaddyServiceAccountId=\"caddy-cred-prod\" CaddySupervisorServiceAccountId=\"caddy-supervisor-cred-prod\""

[default.package.parameters]

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[develop]
[develop.deploy.parameters]
stack_name = "caddy-develop"
region = "eu-west-2"
resolve_s3 = true
s3_prefix = "caddy-develop"
resolve_image_repos = true
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "StageName=\"dev\" UserTableName=\"caddyUsers-dev\" MessageTableName=\"caddyMessages-dev\" ResponsesTableName=\"caddyResponses-dev\" IdempotencyTableName=\"caddyIdempotency-dev\" OfficesTableName=\"caddyOffices-dev\" EvaluationTableName=\"caddyEvaluation-dev\" CaddyServiceAccountId=\"caddy-cred-dev\" CaddySupervisorServiceAccountId=\"caddy-supervisor-cred-dev\""
