PROMPT = """
For example, if the question is "Im 55 and I have a small pension pot. I owe £35,000 in various debts and want to get a DRO. I need my pension for later life. Can I get a DRO or do I need to go bankrupt? I have about £10,000 equity in my house but half of that is my husbands who no longer lives with me." you could respond with:
-----
You can't get a DRO as you have an interest in a property. You also owe more than £30,000 which is the limit for a DRO, although not all debts count towards that.
You could consider bankruptcy but should get debt advice.
There are no eligibility criteria as such for bankruptcy, although it will cost you £680. You might be able to get help with this fee form a charity or trust fund and you can pay this in instalments.
You should be aware that:
Any unapproved pension will be classed as an asset and taken to pay your debts by the person that controls your bankruptcy, known as the Trustee, although you can ask your Trustee to make an agreement not to take your pension but it will be up to the Trustee. You have to ask them within 9 weeks of going bankrupt. You can apply to court to have the pension made exempt within 13 weeks of your bankruptcy, and it will be up to the court what order to make. You should try to get legal advice on what arguments to raise, for instance, if you need to fund any care needs, whether the pension is approved by a foreign tax authority if the pension is from overseas etc
You will not be forced to take any personal pension that is approved as these are protected by law from bankruptcy. However, as you are over 55, you will probably be able to take your pension if you want to. Therefore, the person that agrees you can go bankrupt, known as the Adjudicator, might decide you are still able to pay your debts if the value of your pension after taxes and costs, is more than your debts. You will not be forced to take your pension, but you might not get your bankruptcy order and you would not get your £680 refunded
If you did go bankrupt and drew on your pension, any lump sum might then be claimed by the Trustee and any income you are paid will be used to assess whether you can make payments into an income payment arrangement or order, to repay bankruptcy debts
If you do get a bankruptcy order, the Trustee has 3 years to decide what to do with the equity in your home. They usually won't sell it for at least 1 year after you go bankrupt. You can try to delay this sale but might need to go to court to do so, and the court will only usually delay the sale further if you have exceptional circumstances
You and your husband probably have a 50/50% share of the equity, known as 'beneficial interest.' Therefore, your share of the equity is probably £5000. The Trustee is likely to value your home after 2 years and 3 months to see if there is more equity
If you have more than £5000 equity as your share at that point, the Trustee may apply for a charging order or an order to sell your home. This might happen much sooner if your home goes up in value quickly
If you have less than £5000 the Trustee is unlikely to apply for a charging order or order for sale as there will not be anything left to pay creditors after costs, but this is just a guide of course
A third party could make an offer to buy your share of the property, to the Trustee. You should always take legal advice about this, and be certain that the third party will let you stay in the property
You or your husband may claim to have more than 50% share in the equity, for instance if you paid the entire deposit for the house and used only your funds. This is a complicated area of law and you should get legal advice if you want to claim more or less than 50% share. You should decide this before going bankrupt but any agreement must be for the right consideration
If you later go bankrupt and the Trustee believes you have given away all or part of your equity, in order not to pay creditors, you might have a longer bankruptcy period. This is known as a bankruptcy restriction order, and can last between 2-15 years. The Trustee might also try to seek payment from the other person to recover the lost value, or ask a court to reverse the transaction
The Trustee can review any sale or transfer of assets if they occurred in the 5 years before your bankruptcy if the person you gave away or sold to, was an ‘associate’ like a business partner or family member. There is no time limit where the Trustee thinks you did this on purpose to avoid paying creditors
The Trustee in bankruptcy may argue you have more than 50% in order to claim more funds for creditors, but ultimately only a court can decide the shares
The Trustee may still allow you to sell your home if this will raise more funds, but you should get their consent. However, if you own the home jointly with someone else, you do not need the Trustee’s consent to sell
You should also be aware that bankruptcy will not stop certain creditors chasing you for payment. These are court fines, family or child maintenance arrangements, social fund loans, student loans, debt incurred through fraud, and damages for negligence and injury
----
"""
