name: Dev Deployment

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: sam build -t template.yaml --use-container
      - run: sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region eu-west-2 --parameter-overrides ParameterKey=MessageTableName,ParameterValue=caddyMessages-dev ParameterKey=ResponsesTableName,ParameterValue=caddyResponses-dev ParameterKey=EMBEDDING_MODEL,ParameterValue=model ParameterKey=UserTableName,ParameterValue=caddyUsers-dev ParameterKey=OfficesTableName,ParameterValue=caddyOffices-dev ParameterKey=EvaluationTableName,ParameterValue=caddyEvaluation-dev ParameterKey=CaddyServiceAccountId,ParameterValue=caddy-cred-dev ParameterKey=CaddySupervisorServiceAccountId,ParameterValue=caddy-supervisor-cred-dev ParameterKey=OpensearchUrl,ParameterValue=${{ secrets.OPENSEARCH_URL }} ParameterKey=StageName,ParameterValue=dev --config-env develop --resolve-image-repos
