name: Prod Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Build and push container image
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.CADDY_ECR_ENDPOINT }}
          docker build -f ./caddy_chatbot/Dockerfile -t ${{ secrets.CADDY_ECR_REPO_ID_PROD }}:${{ github.sha }} .
          docker tag ${{ secrets.CADDY_ECR_REPO_ID_PROD }}:${{ github.sha }} ${{ secrets.CADDY_ECR_ENDPOINT }}/${{ secrets.CADDY_ECR_REPO_ID_PROD }}:${{ github.sha }}
          docker push ${{ secrets.CADDY_ECR_ENDPOINT }}/${{ secrets.CADDY_ECR_REPO_ID_PROD }}:${{ github.sha }}
      - name: Deploy infrastructure
        run: |
          aws cloudformation deploy --template-file infra/template.yaml --stack-name "caddy-prod" --capabilities CAPABILITY_NAMED_IAM --parameter-overrides StageName=prod  ParameterKey=MessageTableName,ParameterValue=${{ vars.MESSAGES_TABLE_NAME_PROD }} ParameterKey=ResponsesTableName,ParameterValue=${{ vars.RESPONSES_TABLE_NAME_PROD }} ParameterKey=UserTableName,ParameterValue=${{ vars.USERS_TABLE_NAME_PROD }} ParameterKey=OfficesTableName,ParameterValue=${{ vars.OFFICES_TABLE_NAME_PROD }} ParameterKey=EvaluationTableName,ParameterValue=${{ vars.EVALUATION_TABLE_NAME_PROD }} OpensearchUrl=${{ secrets.OPENSEARCH_URL }} CaddyServiceAccountSecretArn=${{ secrets.CADDY_SA_ARN_PROD }} CaddySupervisorServiceAccountSecretArn=${{ secrets.CADDY_SUPERVISOR_SA_ARN_PROD }} CaddyImage=${{ secrets.CADDY_ECR_ENDPOINT }}/${{ secrets.CADDY_ECR_REPO_ID_PROD }}:${{ github.sha }} CaddySupervisorGoogleCloudProject=${{ secrets.CADDY_SUPERVISOR_GOOGLE_CLOUD_PROJECT_PROD }} CaddyGoogleCloudProject=${{ secrets.CADDY_GOOGLE_CLOUD_PROJECT_PROD }} LLM=${{ vars.LLM }} DomainName=${{ secrets.CERT_DOMAIN }}
