on:
  push:
    branches:
      - main
      - dev
      - lambdas-refactor
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Initalise AWS
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Build Lambda
        run: sam build -t template.yaml --use-container
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install test dependencies
        run: pip install pytest boto3 botocore
      - name: Start lambda endpoint and run tests
        run: |
          sam local start-lambda 2> /dev/null &
          sleep 5
          pytest -v
          pkill -f "sam local start-lambda"
