name: Dev Deployment

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: sam build -t template.yaml --use-container
      - run: sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --parameter-overrides ParameterKey=MessageTableName,ParameterValue=${{ vars.MESSAGES_TABLE_NAME_DEV }} ParameterKey=ResponsesTableName,ParameterValue=${{ vars.RESPONSES_TABLE_NAME_DEV }} ParameterKey=EMBEDDING_MODEL,ParameterValue=model ParameterKey=UserTableName,ParameterValue=${{ vars.USERS_TABLE_NAME_DEV }} ParameterKey=OfficesTableName,ParameterValue=${{ vars.OFFICES_TABLE_NAME_DEV }} ParameterKey=EvaluationTableName,ParameterValue=${{ vars.EVALUATION_TABLE_NAME_DEV }} ParameterKey=OpensearchUrl,ParameterValue=${{ secrets.OPENSEARCH_URL }} ParameterKey=CaddyServiceAccountId,ParameterValue=${{ vars.CADDY_SERVICE_ACCOUNT_ID_DEV }} ParameterKey=CaddySupervisorServiceAccountId,ParameterValue=${{ vars.CADDY_SUPERVISOR_SERVICE_ACCOUNT_ID_DEV }} ParameterKey=StageName,ParameterValue=dev --image-repositories ConversationsFunction=${{ secrets.CADDY_ECR_DEV }} --image-repositories LlmFunction=${{ secrets.CADDY_ECR_DEV }} --image-repositories SuperviseFunction=${{ secrets.CADDY_ECR_DEV }} --config-env develop
