name: FastAPI Dev Deployment

on:
  push:
    branches:
      - enhance/migrateFastAPI

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Build and push container image
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.CADDY_ECR_ENDPOINT }}
          docker build -f ./caddy_chatbot/Dockerfile -t ${{ secrets.CADDY_ECR_REPO_ID_FAST }}:v${{ github.sha }} .
          docker tag ${{ secrets.CADDY_ECR_REPO_ID_FAST }}:v${{ github.sha }} ${{ secrets.CADDY_ECR_ENDPOINT }}/${{ secrets.CADDY_ECR_REPO_ID_FAST }}:v${{ github.sha }}
          docker push ${{ secrets.CADDY_ECR_ENDPOINT }}/${{ secrets.CADDY_ECR_REPO_ID_FAST }}:v${{ github.sha }}
      - name: Deploy infrastructure
        run: |
          aws cloudformation deploy --template-file infra/template.yaml --stack-name "caddy-ecs-fastapi" --capabilities CAPABILITY_NAMED_IAM --parameter-overrides StageName=fast MessageTableName=caddyMessages-fastapi ResponsesTableName=caddyResponse-fastapi EMBEDDING_MODEL=model UserTableName=caddyUsers-fastapi OfficesTableName=caddyOffices-fastapi EvaluationTableName=caddyEvalutation-fastapi OpensearchUrl=${{ secrets.OPENSEARCH_URL }} CaddyServiceAccountSecretArn=${{ secrets.CADDY_SA_ARN_DEV }} CaddySupervisorServiceAccountSecretArn=${{ secrets.CADDY_SUPERVISOR_SA_ARN_DEV }} CaddyImage=${{ secrets.CADDY_ECR_ENDPOINT }}/${{ secrets.CADDY_ECR_REPO_ID_FAST }}:v${{ github.sha }} CaddySupervisorGoogleCloudProject=${{ secrets.CADDY_SUPERVISOR_GOOGLE_CLOUD_PROJECT_DEV }} CaddyGoogleCloudProject=${{ secrets.CADDY_GOOGLE_CLOUD_PROJECT_DEV }} LLM="anthropic.claude-instant-v1" DomainName=${{ secrets.CERT_DOMAIN }}
